# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-05 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=60)),
                ('lastName', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=60)),
                ('packageId', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=60)),
                ('lastName', models.CharField(default='', max_length=60)),
                ('phone', models.CharField(default='', max_length=60)),
                ('licensePlate', models.CharField(default='', max_length=30)),
                ('departureLocation', models.CharField(default='', max_length=30)),
                ('arrivalLocation', models.CharField(default='', max_length=30)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Driver'),
        ),
    ]
